### Site Settings ###
title               : Asaad Al Barwani
description         : >-
                      Computer Science Student
                      at NYU. Gameplay Programmer.
baseurl             : ""                     
repository          : barrwani/barrwani.github.io     
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html


### Author Info ###
author:
  name              : Asaad Al Barwani
  image             : https://i.imgur.com/uyDNQnn.jpg
# behance           : your_username
# dribbble          : your_username
  email             : asaad[dot]barwani[at]gmail[dot]com
# facebook          : your_username
  github            : barrwani
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : barwani
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : barrwani
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /:name





### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id





### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
